
package sky.pdl.counter;

/**
 *
 * @author sky
 */
public class TelaPDL extends javax.swing.JFrame {
    
    //variables
    public int gain;
    public int loss;
    public int result = 0;
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(TelaPDL.class.getName());

    /**
     * Creates new form TelaPDL
     */
    public TelaPDL() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitulo = new javax.swing.JLabel();
        txtGain = new javax.swing.JTextField();
        txtLoss = new javax.swing.JTextField();
        lblGain = new javax.swing.JLabel();
        lblLoss = new javax.swing.JLabel();
        btnVictory = new javax.swing.JButton();
        btnDefeat = new javax.swing.JButton();
        lblPoints = new javax.swing.JLabel();
        btnReset = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblTitulo.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        lblTitulo.setText("LP COUNTER");

        txtGain.addActionListener(this::txtGainActionPerformed);

        lblGain.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblGain.setText("LP gain");

        lblLoss.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblLoss.setText("LP loss");

        btnVictory.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnVictory.setText("victory");
        btnVictory.addActionListener(this::btnVictoryActionPerformed);

        btnDefeat.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnDefeat.setText("defeat");
        btnDefeat.addActionListener(this::btnDefeatActionPerformed);

        lblPoints.setFont(new java.awt.Font("Yu Gothic", 1, 18)); // NOI18N
        lblPoints.setText("0");

        btnReset.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnReset.setText("reset");
        btnReset.addActionListener(this::btnResetActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnReset, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblPoints, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(163, 163, 163))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(76, 76, 76)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(btnVictory, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtGain, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(34, 34, 34)
                                .addComponent(lblGain)))
                        .addGap(55, 55, 55)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblLoss)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(btnDefeat, javax.swing.GroupLayout.DEFAULT_SIZE, 84, Short.MAX_VALUE)
                                .addComponent(txtLoss))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(138, 138, 138)
                        .addComponent(lblTitulo)))
                .addContainerGap(98, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(lblTitulo)
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblLoss)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtLoss))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblGain)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtGain, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnVictory, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDefeat, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(lblPoints)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnReset)
                .addContainerGap(96, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtGainActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtGainActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtGainActionPerformed

    private void btnVictoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVictoryActionPerformed
        gain = Integer.parseInt(txtGain.getText());
        result += gain;
        lblPoints.setText(Integer.toString(result));
    }//GEN-LAST:event_btnVictoryActionPerformed

    private void btnDefeatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDefeatActionPerformed
        loss = Integer.parseInt(txtLoss.getText());
        result -= loss;
        lblPoints.setText(Integer.toString(result));
    }//GEN-LAST:event_btnDefeatActionPerformed

    private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetActionPerformed
        result = 0;
        lblPoints.setText(Integer.toString(result));
    }//GEN-LAST:event_btnResetActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new TelaPDL().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDefeat;
    private javax.swing.JButton btnReset;
    private javax.swing.JButton btnVictory;
    private javax.swing.JLabel lblGain;
    private javax.swing.JLabel lblLoss;
    private javax.swing.JLabel lblPoints;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JTextField txtGain;
    private javax.swing.JTextField txtLoss;
    // End of variables declaration//GEN-END:variables
}
